server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: family-tree-backend
  
  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster.mongodb.net/familytree?retryWrites=true&w=majority
      database: familytree
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 2592000000 # 30 days in milliseconds
  refresh-expiration: 7776000000 # 90 days in milliseconds

# Wasabi S3 Configuration
wasabi:
  access-key: your-access-key
  secret-key: your-secret-key
  bucket-name: family-tree-images
  region: us-east-1
  endpoint: https://s3.wasabisys.com

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,https://your-domain.com
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.familytree: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized