server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: family-tree-backend
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://username:password@cluster.mongodb.net/familytree?retryWrites=true&w=majority}
      database: familytree
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 2592000000 # 30 days in milliseconds
  refresh-expiration: 7776000000 # 90 days in milliseconds

# Wasabi S3 Configuration
wasabi:
  access-key: ${WASABI_ACCESS_KEY:your-access-key}
  secret-key: ${WASABI_SECRET_KEY:your-secret-key}
  bucket-name: ${WASABI_BUCKET_NAME:family-tree-images}
  region: ${WASABI_REGION:us-east-1}
  endpoint: ${WASABI_ENDPOINT:https://s3.wasabisys.com}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,https://your-domain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.familytree: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized